# QA ready image: autologin on tty1 goes straight into the Hyprland session.
[[ -f ~/.bashrc ]] && . ~/.bashrc
if [[ -z "${WAYLAND_DISPLAY:-}" && "$(tty)" == /dev/tty1 ]]; then
    exec ~/.local/bin/qa-session.sh
fi
